version: "2"
services:
  api:
    build:
      context: .
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "5000:5000"
    expose:
      - "5000"
    command: "npm run start"