on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
name: 🚀 Deploy API to Heroku
jobs:
  build:
    name: Building Container 🚀
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build Image and Push it to DockerHub
      uses: docker/build-push-action@v2 
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/actions-workflow-docker-test:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/actions-workflow-docker-test:${{ github.run_number }}