on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
name: 🚀 Deploy API to Heroku
jobs:
  build:
    name: Building Docker Image 🚀
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build Image and Push it to DockerHub
      uses: docker/build-push-action@v2 
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/actions-workflow-docker-test:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/actions-workflow-docker-test:${{ github.sha }}
  deploy: 
    name: Deploying Application to Heroku 🚀
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_path: ''